version: "3"

services:

  # Database
  db:
    image: "mysql:${MYSQL_VERSION}"
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    env_file: ./.env
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - mysql-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: "phpmyadmin:${PHPMYADMIN_VERSION}"
    restart: always
    env_file: ./.env
    ports:
      - "${PHPMYADMIN_LOCAL_PORT}:${PHPMYADMIN_DOCKER_PORT}"
    links:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      PMA_ARBITRARY: 1
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db-data: